language: java

jdk:
- openjdk8
- openjdk9

script: mvn test

matrix:
  include:
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk8
    - arch: ppc64le
      addons: [ apt: [ packages: maven ]]
      jdk: openjdk11
