/*
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.jcodings;
import org.jcodings.constants.EncodingType;
import org.jcodings.constants.EncodingFlag;

final class EncodingList {
    static final EncodingType[] LIST = new EncodingType[] {
        new EncodingType(EncodingFlag.ALIAS, "BINARY", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM437", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP437", "IBM437"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM737", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP737", "IBM737"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM775", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP775", "IBM775"),
        new EncodingType(EncodingFlag.REPLICATE, "CP850", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "IBM850", "CP850"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM852", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "CP852", "IBM852"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM855", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "CP855", "IBM855"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM857", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP857", "IBM857"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM860", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP860", "IBM860"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM861", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP861", "IBM861"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM862", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP862", "IBM862"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM863", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP863", "IBM863"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM864", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP864", "IBM864"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM865", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP865", "IBM865"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM866", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP866", "IBM866"),
        new EncodingType(EncodingFlag.REPLICATE, "IBM869", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP869", "IBM869"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-1258", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.ALIAS, "CP1258", "Windows-1258"),
        new EncodingType(EncodingFlag.REPLICATE, "GB1988", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macCentEuro", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macCroatian", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macCyrillic", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macGreek", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macIceland", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macRoman", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macRomania", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macThai", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macTurkish", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "macUkraine", "ASCII-8BIT"),
        new EncodingType(EncodingFlag.REPLICATE, "CP950", "Big5"),
        new EncodingType(EncodingFlag.SET_BASE, "Big5-HKSCS", "Big5"),
        new EncodingType(EncodingFlag.ALIAS, "Big5-HKSCS:2008", "Big5-HKSCS"),
        new EncodingType(EncodingFlag.REPLICATE, "CP951", "Big5-HKSCS"),
        new EncodingType(EncodingFlag.SET_BASE, "Big5-UAO", "Big5"),
        new EncodingType(EncodingFlag.DUMMY, "IBM037"),
        new EncodingType(EncodingFlag.ALIAS, "ebcdic-cp-us", "IBM037"),
        new EncodingType(EncodingFlag.REPLICATE, "stateless-ISO-2022-JP", "Emacs-Mule"),
        new EncodingType(EncodingFlag.ALIAS, "eucJP", "EUC-JP" /* UI-OSF Application Platform Profile for Japanese Environment Version 1.1 */),
        new EncodingType(EncodingFlag.REPLICATE, "eucJP-ms", "EUC-JP" /* TOG/JVC CDE/Motif Technical WG */),
        new EncodingType(EncodingFlag.ALIAS, "euc-jp-ms", "eucJP-ms"),
        new EncodingType(EncodingFlag.REPLICATE, "CP51932", "EUC-JP"),
        new EncodingType(EncodingFlag.REPLICATE, "EUC-JIS-2004", "EUC-JP" /* defined at JIS X 0213:2004 */),
        new EncodingType(EncodingFlag.ALIAS, "EUC-JISX0213", "EUC-JIS-2004" /* defined at JIS X 0213:2000, and obsolete at JIS X 0213:2004 */),
        new EncodingType(EncodingFlag.ALIAS, "eucKR", "EUC-KR"),
        new EncodingType(EncodingFlag.ALIAS, "eucTW", "EUC-TW"),
        new EncodingType(EncodingFlag.ALIAS, "EUC-CN", "GB2312"),
        new EncodingType(EncodingFlag.ALIAS, "eucCN", "GB2312"),
        new EncodingType(EncodingFlag.REPLICATE, "GB12345", "GB2312"),
        new EncodingType(EncodingFlag.ALIAS, "CP936", "GBK"),
        new EncodingType(EncodingFlag.DUMMY, "ISO-2022-JP"),
        new EncodingType(EncodingFlag.ALIAS, "ISO2022-JP", "ISO-2022-JP"),
        new EncodingType(EncodingFlag.REPLICATE, "ISO-2022-JP-2", "ISO-2022-JP"),
        new EncodingType(EncodingFlag.ALIAS, "ISO2022-JP2", "ISO-2022-JP-2"),
        new EncodingType(EncodingFlag.REPLICATE, "CP50220", "ISO-2022-JP"),
        new EncodingType(EncodingFlag.REPLICATE, "CP50221", "ISO-2022-JP"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-1", "ISO-8859-1"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-2", "ISO-8859-2"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-3", "ISO-8859-3"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-4", "ISO-8859-4"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-5", "ISO-8859-5"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-6", "ISO-8859-6"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-1256", "ISO-8859-6"),
        new EncodingType(EncodingFlag.ALIAS, "CP1256", "Windows-1256"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-7", "ISO-8859-7"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-1253", "ISO-8859-7"),
        new EncodingType(EncodingFlag.ALIAS, "CP1253", "Windows-1253"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-8", "ISO-8859-8"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-1255", "ISO-8859-8"),
        new EncodingType(EncodingFlag.ALIAS, "CP1255", "Windows-1255"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-9", "ISO-8859-9"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-1254", "ISO-8859-9"),
        new EncodingType(EncodingFlag.ALIAS, "CP1254", "Windows-1254"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-10", "ISO-8859-10"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-11", "ISO-8859-11"),
        new EncodingType(EncodingFlag.REPLICATE, "TIS-620", "ISO-8859-11"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-874", "ISO-8859-11"),
        new EncodingType(EncodingFlag.ALIAS, "CP874", "Windows-874"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-13", "ISO-8859-13"),
        new EncodingType(EncodingFlag.REPLICATE, "Windows-1257", "ISO-8859-13"),
        new EncodingType(EncodingFlag.ALIAS, "CP1257", "Windows-1257"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-14", "ISO-8859-14"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-15", "ISO-8859-15"),
        new EncodingType(EncodingFlag.ALIAS, "ISO8859-16", "ISO-8859-16"),
        new EncodingType(EncodingFlag.ALIAS, "CP878", "KOI8-R"),
        new EncodingType(EncodingFlag.REPLICATE, "MacJapanese", "Shift_JIS"),
        new EncodingType(EncodingFlag.ALIAS, "MacJapan", "MacJapanese"),
        new EncodingType(EncodingFlag.ALIAS, "ASCII", "US-ASCII"),
        new EncodingType(EncodingFlag.ALIAS, "ANSI_X3.4-1968", "US-ASCII"),
        new EncodingType(EncodingFlag.ALIAS, "646", "US-ASCII"),
        new EncodingType(EncodingFlag.DUMMY, "UTF-7"),
        new EncodingType(EncodingFlag.ALIAS, "CP65000", "UTF-7"),
        new EncodingType(EncodingFlag.ALIAS, "CP65001", "UTF-8"),
        new EncodingType(EncodingFlag.REPLICATE, "UTF8-MAC", "UTF-8"),
        new EncodingType(EncodingFlag.ALIAS, "UTF-8-MAC", "UTF8-MAC"),
        new EncodingType(EncodingFlag.ALIAS, "UTF-8-HFS", "UTF8-MAC" /* Emacs 23.2 */),
        new EncodingType(EncodingFlag.DUMMY_UNICODE, "UTF-16"),
        new EncodingType(EncodingFlag.DUMMY_UNICODE, "UTF-32"),
        new EncodingType(EncodingFlag.ALIAS, "UCS-2BE", "UTF-16BE"),
        new EncodingType(EncodingFlag.ALIAS, "UCS-4BE", "UTF-32BE"),
        new EncodingType(EncodingFlag.ALIAS, "UCS-4LE", "UTF-32LE"),
        new EncodingType(EncodingFlag.ALIAS, "CP932", "Windows-31J"),
        new EncodingType(EncodingFlag.ALIAS, "csWindows31J", "Windows-31J" /* IANA.  IE6 don't accept Windows-31J but csWindows31J. */),
        new EncodingType(EncodingFlag.ALIAS, "SJIS", "Windows-31J"),
        new EncodingType(EncodingFlag.ALIAS, "PCK", "Windows-31J"),
        new EncodingType(EncodingFlag.ALIAS, "CP1250", "Windows-1250"),
        new EncodingType(EncodingFlag.ALIAS, "CP1251", "Windows-1251"),
        new EncodingType(EncodingFlag.ALIAS, "CP1252", "Windows-1252"),
        new EncodingType(EncodingFlag.REPLICATE, "UTF8-DoCoMo", "UTF-8"),
        new EncodingType(EncodingFlag.REPLICATE, "SJIS-DoCoMo", "Windows-31J"),
        new EncodingType(EncodingFlag.REPLICATE, "UTF8-KDDI", "UTF-8"),
        new EncodingType(EncodingFlag.REPLICATE, "SJIS-KDDI", "Windows-31J"),
        new EncodingType(EncodingFlag.REPLICATE, "ISO-2022-JP-KDDI", "ISO-2022-JP"),
        new EncodingType(EncodingFlag.REPLICATE, "stateless-ISO-2022-JP-KDDI", "stateless-ISO-2022-JP"),
        new EncodingType(EncodingFlag.REPLICATE, "UTF8-SoftBank", "UTF-8"),
        new EncodingType(EncodingFlag.REPLICATE, "SJIS-SoftBank", "Windows-31J")
    };
}